# Generated by Django 5.2.4 on 2025-07-25 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=100)),
                ('deprecated', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Crypto_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolioCripto.crypto')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolioCripto.crypto')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolioCripto.wallet')),
            ],
        ),
    ]
