# Generated by Django 5.2.4 on 2025-08-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolioCripto', '0002_alter_crypto_price_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buy_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
