# Generated by Django 5.2.4 on 2025-08-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolioCripto', '0003_transaction_buy_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='color',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='logo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
