# Generated by Django 5.2.4 on 2025-08-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolioCripto', '0004_wallet_color_wallet_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='logo',
            new_name='icon',
        ),
    ]
